######################################################################
# Automatically generated by qmake (3.0) Mon Feb 13 18:37:30 2017
######################################################################

TEMPLATE = app
TARGET = HelloWorldGUI
INCLUDEPATH += .

QT += widgets

# Input
SOURCES += main.cpp
