######################################################################
# Automatically generated by qmake (3.0) Mon Feb 13 18:17:37 2017
######################################################################

TEMPLATE = app
TARGET = QtHelloWorld
INCLUDEPATH += .

# Input
SOURCES += main.cpp
